# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('bikes', models.IntegerField(blank=True, null=True)),
                ('docks', models.IntegerField(blank=True, null=True)),
                ('poll_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'counts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefStation',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('max_total', models.IntegerField(blank=True, null=True)),
                ('jurisdiction', models.TextField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_stations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('poll_time', models.IntegerField(blank=True, null=True)),
                ('curr_total', models.IntegerField(blank=True, null=True)),
                ('max_total', models.IntegerField(blank=True, null=True)),
                ('bikes', models.IntegerField(blank=True, null=True)),
                ('docks', models.IntegerField(blank=True, null=True)),
                ('lc', models.IntegerField(blank=True, null=True)),
                ('lu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': True,
            },
        ),
    ]
