# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='available_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='defective_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
